### ISSUE TITLE
I am able to register through postman successfully which is reflected in my database but while registering through frontend nothing is reflected and while signing in through localhost via postman it is showing "TypeError: db.select is not a function"

### ISSUE THREAD

**Issue by whatislifeworth** [aneagoie/smart-brain-api#9]
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>TypeError: db.select is not a function<br> &nbsp; &nbsp;at Object.handleSignIn (C:\Users\Administrator\Desktop\node\controllers\signin.js:2:5)<br> &nbsp; &nbsp;at C:\Users\Administrator\Desktop\node\server.js:30:38<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\index.js:335:12)<br> &nbsp; &nbsp;at next (C:\Users\Administrator\Desktop\node\node_modules\express\lib\router\index.js:275:10)<br> &nbsp; &nbsp;at C:\Users\Administrator\Desktop\node\node_modules\body-parser\lib\read.js:130:5</pre>
</body>

</html>

**Comment by whatislifeworth** [comment]
It was just a silly error. I forgot to install clarifai package in the backend.
